### ISSUE TITLE
Please handle password less ssh/scp case.

### ISSUE THREAD

**Issue by ashguptablr** [Juniper/splitcopy#1]
I have password less ssh configured to remote server.
'splitcopy' ask for password, when it can directly login to remote shell.

ashgupta@server:$ splitcopy --get --scp foobar ashgupta@someotherserver
Password:   <<<<<<<<<<<<<<<<

ashgupta@server:$ ssh someotherserver
Last login: Mon Apr  6 05:07:17 2020 from 10.224.160.87
someotherserver:~>

--Regards,
Ashish Gupta

**Comment by ipmonk** [comment]
fixed in release v1.0.12
