### ISSUE TITLE
'tcsh' support in script.

### ISSUE THREAD

**Issue by ashguptablr** [Juniper/splitcopy#2]
'splitcopy' looks like expecting some well known shell prompt on remote server.
If 'splicopy' doesn't find these known prompt, it bails out.
Can you please add support for 'tcsh' shell prompt case also?

Regards,
--Ashish Gupta

server:~> echo $SHELL
/bin/tcsh  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
server:~>

**Comment by ipmonk** [comment]
Thanks for the issue report Ashish.
The issue comes from the junos-pyez StartShell class. 
I've raised a pull request to fix that, but it breaks another use case. 
If it can't be resolved, I'll replace pyez with a pure ssh implementation in a future release.

**Comment by ashguptablr** [comment]
Workaround is working for me for now.
As script expect bash shell on remote server login, I have changed shell by exec it explicitly from .login.

ashgupta@remoteserver:~$ cat .login
[ -x /usr/games/fortune ] && /usr/games/fortune freebsd-tips
exec bash   

We can close it for now. You can create enhancement ticket internally.

**Comment by ipmonk** [comment]
fixed in version 1.1.0
